version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Pa$$w0rd"
      MYSQL_DATABASE: luciq_chat_system_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pPa$$w0rd"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - action.destructive_requires_name=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  migrations:
    build: .
    command: bundle exec rails db:migrate
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PASSWORD: "Pa$$w0rd"
    restart: "no"

  elasticsearch_setup:
    build: .
    command: bundle exec rake elasticsearch:setup
    depends_on:
      elasticsearch:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_PASSWORD: "Pa$$w0rd"
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200
    restart: "no"

  api:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      elasticsearch_setup:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PASSWORD: "Pa$$w0rd"
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      elasticsearch_setup:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PASSWORD: "Pa$$w0rd"
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200

volumes:
  mysql_data:
  redis_data:
  es_data: